### ISSUE TITLE
Memory leaks using local rendering device

### ISSUE THREAD

**Issue by VanessB** [wardensdev/ComputeWorker#1]
Hello! I have also been working with compute shaders recently and came across this this bug in Godot engine: [issue#71003](https://github.com/godotengine/godot/issues/71003). I have not tested Your extension, but from the first look it seems that it is vulnerable to this bug, because You create local rendering device once on class initialization and do not `free()` it manually. This can potentially lead to the following:
1. The engine will crash on reaching certain number of `ComputeWorker`s (199 in my case, see example project in the mentioned issue).
2. Each `ComputeWorker` will leak memory on destruction.

I hope this will save some of Your time. :)

**Comment by wardensdev** [comment]
Thanks for the info! I was not aware of this bug when I submitted this extension to the asset library. I will take a look at it and add in the freeing of resources. I'll update the README to include mention of this bug in the meantime.

**Comment by wardensdev** [comment]
Commit [#11649dd8](https://github.com/wardensdev/ComputeWorker/commit/11649dd847a357a79512da11209f1039d7d58f97) fixes the memory leak issue. On `_exit_tree()` the ComputeWorker will now free all RenderingDevice resources before freeing the RenderingDevice itself.

**Comment by VanessB** [comment]
A comment regarding crashes on too many of `ComputeWorker`s: may be it is worth creating local rendering device only on shader execution and destroying it after (i.e. not having it as a class member)?

**Comment by wardensdev** [comment]
I'm not sure if it would be worth it to implement that verbatim. You could do something like call `destroy()` after running the worker, and `initialize()` the worker again to achieve the same effect without freeing the node. That would work well for keeping the number of concurrent rendering devices down. This will require a small change to the `initialize()` function to check if there is an `rd`. I'll add that in hopefully today.

**Comment by wardensdev** [comment]
I've updated the `initialize()` and `destroy()` functions to make the ComputeWorker able to start and stop at will. Calling `destroy()` will free all the RenderingDevice resources and the RD itself, setting `var initialized` to false. Then you can swap out shaders, uniforms, etc. and start it back up again with a new RD by calling `initialize()`.
