### ISSUE TITLE
Add Example to return array

### ISSUE THREAD

**Issue by Bimbam360** [wardensdev/ComputeWorker#6]
Firstly, thanks for putting this together, as it reduces the horrors of compute shader complexity (though still complex for me at least).

Would it be possible to include an example where the compute shader returns an array, as my implementation is returning the following error when using GPU_PackedFloat64Array:
"Trying to assign an array of type "Array" to a variable of type "Array[float]"."

**Comment by wardensdev** [comment]
Thanks for opening an issue for this. This was an oversight on my part. The GPU_PackedFloat64Array and GPU_PackedVector3Array classes were written to take in standard `Array` types. I've already made the changes to remedy this, so they will take in their respective `Packed***` data types. I've also refined them a bit, so now they have an `array_size` variable in the editor to define the array's size if `data` is left empty when the ComputeWorker is initialized. And I've updated the example script and scene to demonstrate both dynamic and static sized arrays.

It usually takes a day or two for updates to be accepted to the asset library, but you can clone `master` to get the changes now.

**Comment by wardensdev** [comment]
> Firstly, thanks for putting this together, as it reduces the horrors of compute shader complexity (though still complex for me at least).

Feel free to drop any feedback you have in an issue. The goal of this project is to make compute shaders more accessible, so any input is welcome!
